CREATE TABLE CLASS_NUM (
    SCHOOL_CD CHAR(3),
    CLASS_NUM VARCHAR(5),
    PRIMARY KEY (SCHOOL_CD, CLASS_NUM)
);

CREATE TABLE SCHOOL (
    CD CHAR(3) PRIMARY KEY,
    NAME VARCHAR(20),
);

CREATE TABLE STUDENT (
    NO VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(10),
    ENT_YEAR INTEGER(10),
    CLASS_NUM CHAR(3),
    IS_ATTEND BOOLEAN,
    SCHOOL_CD CHAR(3),
);

CREATE TABLE SUBJECT (
    SCHOOL_CD CHAR(3),
    CD CHAR(3),
    NAME VARCHAR(20),
    PRIMARY KEY (SCHOOL_CD, CD)
);

CREATE TABLE TEACHER (
    ID VARCHAR(10) PRIMARY KEY,
    PASSWORD VARCHAR(30),
    NAME VARCHAR(10),
    SCHOOL_CD CHAR(3),
);

CREATE TABLE TEST (
    STUDENT_NO VARCHAR(10),
    SUBJECT_CD CHAR(3),
    SCHOOL_CD CHAR(3),
    NO INTEGER(10),
    POINT INTEGER(10),
    CLASS_NUM CHAR(5),
    PRIMARY KEY (STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO),
);
